config/routes.rb
Rails.application.routes.draw do
  resources :onsens
  get "users/:id/likes"=>"users#likes"
  get "users/:id/makes" =>"users#makes"
  post "likes/:list_id/create"=>"likes#create"

  post "likes/:list_id/destroy"=>"likes#destroy"


  get "login"=>"users#login_form"
  post"login"=>"users#login"

  get "logout"=>"users#logout"

  get 'users/index'=>"users#index"
  get "users/new"=>"users#new"
  get"users/:id" => "users#show"
  post "users/create"=>"users#create"
  get"users/:id/edit"=>"users#edit"
  post "users/:id/update" => "users#update"
  post "users/:id/destroy" => "users#destroy"



  get 'lists/index'
  get "lists/new"=>"lists#new"
  get "lists/new"=>"lists#new_onsen"
  get"lists/:id" => "lists#show"
  post "lists/create"=>"lists#create"
  get"lists/:id/edit"=>"lists#edit"
  post "lists/:id/update" => "lists#update"
  post "lists/:id/destroy" => "lists#destroy"

  get '/' =>"home#top"
  get '/about'=>"home#about"
  get 'posts/:id' => "posts#show"
end

app/models/onsen.rb
class Onsen < ApplicationRecord

  has_many :lists, dependent: :destroy
  belongs_to :user
  validates :name,{length:{maximum: 20}}
  validates :name, uniqueness: true

enum prefecture_id: {
北海道:0,
青森県:1,
岩手県:2,
宮城県:3,
秋田県:4,
山形県:5,
福島県:6,
茨城県:7,
栃木県:8,
群馬県:9,
埼玉県:10,
千葉県:11,
東京都:12,
神奈川県:13,
新潟県:14,
富山県:15,
石川県:16,
福井県:17,
山梨県:18,
長野県:19,
岐阜県:20,
静岡県:21,
愛知県:22,
三重県:23,
滋賀県:24,
京都府:25,
大阪府:26,
兵庫県:27,
奈良県:28,
和歌山県:29,
鳥取県:30,
島根県:31,
岡山県:32,
広島県:33,
山口県:34,
徳島県:35,
香川県:36,
愛媛県:37,
高知県:38,
福岡県:39,
佐賀県:40,
長崎県:41,
熊本県:42,
大分県:43,
宮崎県:44,
鹿児島県:45,
沖縄県:46}


#ユーザー名による絞り込み
scope :get_by_name, ->(name) {
where("name like ?", "%#{name}%")
}
#都道府県による絞り込み
scope :get_by_prefecture_id, ->(prefecture_id) {where(prefecture_id: prefecture_id)}
end
#(prefecture_id) 受け取った値に命名したもの

app/controllers/onsens_controller.rb
class OnsensController < ApplicationController
  before_action :set_onsen, only: [:show, :edit, :update, :destroy]

  # GET /onsens
  # GET /onsens.json
  def index
   @onsens = Onsen.all
    if params[:name].present?
    @onsens = @onsens.get_by_name params[:name]
    elsif params[:onsen].present? && params[:onsen][:prefecture_id].present?  then
    logger.debug(params[:onsen])
    @onsens = @onsens.get_by_prefecture_id params[:onsen][:prefecture_id]
   # logger.debug(params[:onsen][:prefecture_id])
    else
    @onsens = Onsen.all
    end
  end

    # if params[:onsen].nil?
    #   @onsens = Onsen.all
    # else

  #   if params[:onsen][:prefecture_id].present?
  #   @onsens = @onsens.get_by_prefecture_id params[:onsen][:prefecture_id]
  # else
  #       logger.debug(params[:onsen][:prefecture_id])
  #   end
  #
  #   logger.debug("[debug] @onsens")
  #   end
  #  # end

  # GET /onsens/1
  # GET /onsens/1.json
  def show
  end

  # GET /onsens/new
  def new
    @onsen = Onsen.new(user_id: @current_user.id)

  end

  # GET /onsens/1/edit
  def edit
  end

  # POST /onsens
  # POST /onsens.json
  def create
    @onsen = Onsen.new(onsen_params)

    respond_to do |format|
      if @onsen.save
        format.html { redirect_to @onsen, notice: 'Onsen was successfully created.' }
        format.json { render :show, status: :created, location: @onsen }
      else
        format.html { render :new }
        format.json { render json: @onsen.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /onsens/1
  # PATCH/PUT /onsens/1.json
  def update
    respond_to do |format|
      if @onsen.update(onsen_params)
        format.html { redirect_to @onsen, notice: 'Onsen was successfully updated.' }
        format.json { render :show, status: :ok, location: @onsen }
      else
        format.html { render :edit }
        format.json { render json: @onsen.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /onsens/1
  # DELETE /onsens/1.json
  def destroy
    @onsen.destroy
    respond_to do |format|
      format.html { redirect_to onsens_url, notice: 'Onsen was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_onsen
      @onsen = Onsen.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def onsen_params
      params.require(:onsen).permit(:name, :prefecture_id, :url, :review, :list_id, :user_id)
    end
end

app/helpers/onsens_helper.rb
module OnsensHelper
end

app/views/onsens/_form.html.erb
<div class='onsen-form'>
<%= form_with(model: onsen, local: true) do |form| %>
  <%= form.hidden_field :user_id  %>
  <% if onsen.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(onsen.errors.count, "error") %> prohibited this onsen from being saved:</h2>

      <ul>
      <% onsen.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :温泉名 %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :都道府県 %>

    <%= form.select :prefecture_id, [  ['北海道地方', [
        ['北海道',   '北海道'],
      ]
    ],
    ['東北地方', [
        ['青森県',    '青森県'],
        ['岩手県',   '岩手県'],
        ['宮城県',   '宮城県'],
        ['秋田県',   '秋田県'],
        ['山形県',   '山形県'],
        ['福島県',   '福島県'],
      ]
    ],
    ['関東地方', [
        ['東京都',   '東京都'],
        ['埼玉県',   '埼玉県'],
        ['千葉県',   '千葉県'],
        ['神奈川県',   '神奈川県'],
        ['茨城県',    '茨城県'],
        ['栃木県',   '栃木県'],
        ['群馬県',   '群馬県'],
      ]
    ],
    ['中部地方', [
        ['静岡県',   '静岡県'],
        ['愛知県',   '愛知県'],
        ['新潟県',    '新潟県'],
        ['富山県',   '富山県'],
        ['石川県',   '石川県'],
        ['福井県',   '福井県'],
        ['山梨県',   '山梨県'],
        ['長野県',   '長野県'],
        ['岐阜県',   '岐阜県'],
      ]
    ],
    ['近畿地方', [
        ['大阪府',   '大阪府'],
        ['京都府',   '京都府'],
        ['兵庫県',   '兵庫県'],
        ['奈良県',   '奈良県'],
        ['三重県',    '三重県'],
        ['滋賀県',   '滋賀県'],
        ['和歌山県',   '和歌山県'],
      ]
    ],
    ['中国地方', [
        ['岡山県',   '岡山県'],
        ['広島県',   '広島県'],
        ['鳥取県',    '鳥取県'],
        ['島根県',   '島根県'],
        ['山口県',   '山口県'],
      ]
    ],
    ['四国地方', [
        ['徳島県',    '徳島県'],
        ['香川県',   '香川県'],
        ['愛媛県',   '愛媛県'],
        ['高知県',   '高知県'],
      ]
    ],
    ['九州地方', [
        ['福岡県',    '福岡県'],
        ['佐賀県',   '佐賀県'],
        ['長崎県',   '長崎県'],
        ['熊本県',   '熊本県'],
        ['大分県',   '大分県'],
        ['宮崎県',   '宮崎県'],
        ['鹿児島県',   '鹿児島県'],
      ]
    ],
    ['沖縄地方', [
        ['沖縄県',    '沖縄県'],
      ]
    ],
  ]
 %>
  </div>

  <div class="field">
    <%= form.label :HP %>
    <%= form.text_field :url %>
  </div>

  <div class="field">
    <%= form.label :レビュー %>
    <%= form.text_field :review %>
  </div>

  <div class="actions">
    <%= form.submit %>
    <%= link_to '戻る', onsens_path %>
  </div>
<% end %>
</div>

app/views/onsens/edit.html.erb
<div class='onsen-index-body'>

<h1>温泉情報を編集する</h1>

<%= render 'form', onsen: @onsen %>

<%= link_to '投稿詳細', @onsen %> |
<%= link_to '一覧へ戻る', onsens_path %>
</div>

app/views/onsens/index.html.erb
<div class='onsen-index-body'>
<p id="notice"><%= notice %></p>

<h1>温泉一覧</h1>

<div>
<%= form_tag(onsens_path, method: "get") do %>
<%= label_tag :name, "温泉名" %><%= text_field_tag :name, params[:name] %>
<%= label_tag :prefecture_id, "都道府県" %><%= select :onsen, :prefecture_id, Onsen.prefecture_ids, {prompt: '選択してください'}%>


<%= submit_tag "検索" %>

<% end %>
</div>
<table div class='onsen-table'>
  <thead>
    <tr>
      <th>温泉名</th>
      <th>県</th>
      <th></th>
      <th>レビュー</th>
      <th>投稿者</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @onsens.each do |onsen| %>
      <tr>
        <td><%= onsen.name %></td>
        <td><%= onsen.prefecture_id%></td>
        <%if onsen.url.nil? then%>
        <td><%=  %></td>
        <%else%>
        <td><%= link_to 'HP', onsen.url%>
        <%end%>
        <%if onsen.review.nil? then%>
        <td><%=  %></td>
        <%else%>
        <td><%= link_to 'レビュー', onsen.review %></td>
        <%end%>
        <td><%= onsen.user.name%></td>

        <td><%= link_to '詳細', onsen %></td>
        <!-- <td><%= link_to '編集', edit_onsen_path(onsen) %></td>
        <td><%= link_to '削除', onsen, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table >

<br>

<%= link_to '新しい温泉を登録する', new_onsen_path %>

</div>

app/views/onsens/new.html.erb
<h1>New Onsen</h1>

<%= render 'form', onsen: @onsen %>

app/views/onsens/show.html.erb
<div class='onsen-show'>
<p id="notice"><%= notice %></p>

<p>
  <strong>温泉名:</strong>
  <%= @onsen.name %>
</p>

<p>
  <strong>県:</strong>
  <%= @onsen.prefecture_id %>
</p>

<p>
  <strong>HP:</strong>
  <%= link_to 'HPを表示', @onsen.url, :target=>["_blank"]%>
</p>

<p>
  <strong>レビュー:</strong>
  <%= link_to '口コミを表示', @onsen.review, :target=>["_blank"] %>
</p>

<p>
  <strong>投稿:</strong><%=@onsen.user.name%>
</p>

<%= link_to '編集', edit_onsen_path(@onsen) %>
<%= link_to"削除","/onsens/#{@onsen.id}",{method:"delete"}%>

<%= link_to '投稿', :controller=>'lists', :action =>'new', id: @onsen.id  %>
<%= link_to '戻る', onsens_path %>
</div>